name: task_flow
description: "A Flutter task management application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
    
  equatable: ^2.1.0
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management
  flutter_bloc: ^9.1.1

  # Routing
  go_router: ^16.2.1

  # Networking
  dio: ^5.8.0

  # Fonts

  # SVG
  flutter_svg: ^2.2.0

  # UI
  gap: ^3.0.1

  # Local Storage
  shared_preferences: ^2.5.3

  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/logos/